name: lenskit-auto
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12.9
  - numpy>=2.2.6
  - pandas>=2.2.3
  - scikit-learn>=1.6.1
  - scipy>=1.15.3
  - matplotlib>=3.10.3
  - numba>=0.61.2
  - pip:
      - lenskit==2025.2.0
      - smac==2.3.1
